[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache_forge"

[profile.default.optimizer]
enabled = true
runs = 200

[profile.default.model_checker]
contracts = { '/src' = ['all] }
engine = 'chc'
timeout = 10000
targets = ['assert', 'underflow', 'overflow', 'divByZero', 'constantCondition', 'popEmptyArray', 'outOfBounds']

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
